local require = require('neviraide-ui.utils.lazy')

local Api = require('neviraide-ui.api')
local Config = require('neviraide-ui.config')

local M = {}

M.api = Api

---Setup configuration
---@param opts? NeviraideUIConfig
function M.setup(opts)
  local function load()
    require('neviraide-ui.utils').try(function()
      require('neviraide-ui.buftabline.lazyload')

      require('neviraide-ui.config').setup(opts)
      require('neviraide-ui.commands').setup()
      require('neviraide-ui.message.router').setup()

      vim.opt.statusline = '%!v:lua.require("neviraide-ui.statusline").run()'

      require('usercommands')

      vim.defer_fn(function()
        local bufs = vim.api.nvim_list_bufs()

        if #vim.fn.argv() == 0 and (#bufs == 1 and bufs[1] == 1) then
          require('neviraide-ui.dashboard').open()
          vim.api.nvim_exec2(':bd#', { output = true })
        end
      end, 0)

      require('autocommands')

      require('neviraide-ui.override_vim_ui.input')
      require('neviraide-ui.override_vim_ui.select')

      require('neviraide-ui.themes').load_all_highlights()
      M.enable()
    end)
  end

  if vim.v.vim_did_enter == 0 then
    -- Schedule loading after VimEnter. Get the UI up and running first.
    vim.api.nvim_create_autocmd('VimEnter', {
      once = true,
      callback = load,
    })
  else
    -- Schedule on the event loop
    vim.schedule(load)
  end
end

function M.disable()
  Config._running = false
  if Config.options.notify.enabled then
    require('neviraide-ui.source.notify').disable()
  end
  require('neviraide-ui.message.router').disable()
  require('neviraide-ui.ui').disable()
  require('neviraide-ui.utils.hacks').disable()
end

M.deactivate = M.disable

function M.cmd(name) require('neviraide-ui.commands').cmd(name) end

function M.enable()
  Config._running = true
  if Config.options.notify.enabled then
    require('neviraide-ui.source.notify').enable()
  end

  local hyprTheme = require('neviraide-ui.hyprland.utils').get_theme_from_hypr()
  require('neviraide-ui.utils.change_theme').change_theme(hyprTheme)

  require('neviraide-ui.utils.hacks').enable()
  require('neviraide-ui.ui').enable()
  require('neviraide-ui.message.router').enable()
end

-- Redirect any messages generated by a command or function
---@param cmd string|fun() command or function to execute
---@param routes? NeviraideUIRouteConfig[] custom routes. Defaults to `config.redirect`
function M.redirect(cmd, routes)
  return require('neviraide-ui.message.router').redirect(cmd, routes)
end

---@param msg string
---@param level number|string
---@param opts? table<string, any>
function M.notify(msg, level, opts)
  return require('neviraide-ui.source.notify').notify(msg, level, opts)
end

return M
