---@alias BorderType "'none'"|"'single'"|"'double'"|"'rounded'"|"'solid'"|"'shadow'"
---@alias BorderChars "{'','','','','','','',''}"|"{'─','│','─','│','┌','┐','┘','└'}"|"{'═','║','═','║','╔','╗','╝','╚'}"|"{'─','│','─','│','╭','╮','╯','╰'}"|"{' ',' ',' ',' ',' ',' ',' ',' '}"
---@alias ThemeType "'dark'"|"'light'"
---@alias HydeThemes "'Gruvbox-Retro'"|"'Decay-Green'"|"'Catppuccin-Latte'"|"'Catppuccin-Mocha'"|"'Cyberpunk-Edge'"|"'Frosted-Glass'"|"'Graphite-Mono'"|"'Material-Sakura'"|"'Rose-Pine'"|"'Tokyo-Night'"|"'One-Dark'"|"'Synth-Wave'"
