local colors = require('neviraide-ui.themes').get_theme_tb('base_16')
local kitty = require('neviraide-ui.hyprland.utils').colors.kitty

-- vim.g.terminal_color_0 = colors.base01
-- vim.g.terminal_color_1 = colors.base08
-- vim.g.terminal_color_2 = colors.base0B
-- vim.g.terminal_color_3 = colors.base0A
-- vim.g.terminal_color_4 = colors.base0D
-- vim.g.terminal_color_5 = colors.base0E
-- vim.g.terminal_color_6 = colors.base0C
-- vim.g.terminal_color_7 = colors.base05
-- vim.g.terminal_color_8 = colors.base03
-- vim.g.terminal_color_9 = colors.base08
-- vim.g.terminal_color_10 = colors.base0B
-- vim.g.terminal_color_11 = colors.base0A
-- vim.g.terminal_color_12 = colors.base0D
-- vim.g.terminal_color_13 = colors.base0E
-- vim.g.terminal_color_14 = colors.base0C
-- vim.g.terminal_color_15 = colors.base07

vim.g.terminal_color_0 = kitty.black
vim.g.terminal_color_1 = kitty.red
vim.g.terminal_color_2 = kitty.blue
vim.g.terminal_color_3 = kitty.yellow
vim.g.terminal_color_4 = kitty.green
vim.g.terminal_color_5 = kitty.magenta
vim.g.terminal_color_6 = kitty.cyan
vim.g.terminal_color_7 = kitty.white
vim.g.terminal_color_8 = kitty.bright_black
vim.g.terminal_color_9 = kitty.bright_red
vim.g.terminal_color_10 = kitty.bright_blue
vim.g.terminal_color_11 = kitty.bright_yellow
vim.g.terminal_color_12 = kitty.bright_green
vim.g.terminal_color_13 = kitty.bright_magenta
vim.g.terminal_color_14 = kitty.bright_cyan
vim.g.terminal_color_15 = kitty.bright_white
