local color = require('neviraide-ui.themes.colors').palette

return {
  ['@variable'] = { fg = color.white },
  ['@variable.builtin'] = { fg = color.yellow },
  ['@variable.parameter'] = { fg = color.bright_red },
  ['@variable.member'] = { fg = color.bright_red },
  ['@variable.member.key'] = { fg = color.bright_red },

  ['@module'] = { fg = color.bright_red },
  -- ["@module.builtin"] = { fg = color.bright_red },

  ['@constant'] = { fg = color.bright_red },
  ['@constant.builtin'] = { fg = color.yellow },
  ['@constant.macro'] = { fg = color.bright_red },

  ['@string'] = { fg = color.green },
  ['@string.regex'] = { fg = color.cyan },
  ['@string.escape'] = { fg = color.cyan },
  ['@character'] = { fg = color.bright_red },
  -- ["@character.special"] = { fg = color.bright_red },
  ['@number.float'] = { fg = color.yellow },

  ['@annotation'] = { fg = color.red },
  ['@attribute'] = { fg = color.bright_yellow },
  ['@error'] = { fg = color.bright_red },

  ['@keyword.exception'] = { fg = color.bright_red },
  ['@keyword'] = { fg = color.magenta, italic = true },
  ['@keyword.function'] = { fg = color.magenta },
  ['@keyword.return'] = { fg = color.magenta, italic = true },
  ['@keyword.operator'] = { fg = color.magenta },
  ['@keyword.import'] = { link = 'Include' },
  ['@keyword.conditional'] = { fg = color.magenta },
  ['@keyword.conditional.ternary'] = { fg = color.magenta },
  ['@keyword.repeat'] = { fg = color.bright_yellow },
  ['@keyword.storage'] = { fg = color.bright_yellow },
  ['@keyword.directive.define'] = { fg = color.magenta },
  ['@keyword.directive'] = { fg = color.bright_yellow },

  ['@function'] = { fg = color.blue },
  ['@function.builtin'] = { fg = color.blue },
  ['@function.macro'] = { fg = color.bright_red },
  ['@function.call'] = { fg = color.blue },
  ['@function.method'] = { fg = color.blue },
  ['@function.method.call'] = { fg = color.blue },
  ['@constructor'] = { fg = color.cyan },

  ['@operator'] = { fg = color.white },
  ['@reference'] = { fg = color.white },
  ['@punctuation.bracket'] = { fg = color.red },
  ['@punctuation.delimiter'] = { fg = color.red },
  ['@symbol'] = { fg = color.green },
  ['@tag'] = { fg = color.bright_yellow },
  ['@tag.attribute'] = { fg = color.bright_red },
  ['@tag.delimiter'] = { fg = color.red },
  ['@text'] = { fg = color.white },
  ['@text.emphasis'] = { fg = color.yellow },
  ['@text.strike'] = { fg = color.red, strikethrough = true },
  ['@type.builtin'] = { fg = color.bright_yellow },
  ['@definition'] = { sp = color.grey, underline = true },
  ['@scope'] = { bold = true },
  ['@property'] = { fg = color.bright_red },

  -- markup
  ['@markup.heading'] = { fg = color.blue },
  ['@markup.raw'] = { fg = color.yellow },
  ['@markup.link'] = { fg = color.bright_red },
  ['@markup.link.url'] = { fg = color.yellow, underline = true },
  ['@markup.link.label'] = { fg = color.cyan },
  ['@markup.list'] = { fg = color.bright_red },
  ['@markup.strong'] = { bold = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.quote'] = { bg = color.black2 },

  ['@comment'] = { fg = color.grey_fg },
  ['@comment.todo'] = { fg = color.grey, bg = color.white },
  ['@comment.warning'] = { fg = color.black2, bg = color.yellow },
  ['@comment.note'] = { fg = color.black2, bg = color.white },
  ['@comment.danger'] = { fg = color.black2, bg = color.red },

  ['@diff.plus'] = { fg = color.green },
  ['@diff.minus'] = { fg = color.red },
  ['@diff.delta'] = { fg = color.light_grey },
}
