local palette = require('neviraide-ui.icons.utils').palette
local i = require('neviraide-ui.icons.utils').icon_decoder

return {
  ['svg'] = { icon = i(61801), color = palette.orange, name = 'Svg' },
  ['git'] = {
    icon = i(61784),
    color = palette.bright_black,
    name = 'GitLogo',
  },
  ['.gitattributes'] = {
    icon = i(61784),
    color = palette.bright_black,
    name = 'GitAttributes',
  },
  ['.gitconfig'] = {
    icon = i(61784),
    color = palette.bright_black,
    name = 'GitConfig',
  },
  ['.gitignore'] = {
    icon = i(61784),
    color = palette.bright_black,
    name = 'GitIgnore',
  },
  ['.gvimrc'] = {
    icon = i(61932),
    color = palette.bright_green,
    name = 'Gvimrc',
  },
  ['.npmignore'] = {
    icon = i(61843),
    color = palette.bright_red,
    name = 'NPMIgnore',
  },
  ['.vimrc'] = {
    icon = i(61932),
    color = palette.bright_green,
    name = 'Vimrc',
  },
  ['.zshrc'] = {
    icon = i(61911),
    color = palette.bright_black,
    name = 'Zshrc',
  },
  ['Dockerfile'] = {
    icon = i(61758),
    color = palette.bright_blue,
    name = 'Dockerfile',
  },
  ['Gemfile$'] = {
    icon = i(61880),
    color = palette.bright_red,
    name = 'Gemfile',
  },
  ['LICENSE'] = {
    icon = i(61767),
    color = palette.yellow,
    name = 'License',
  },
  ['bash'] = {
    icon = i(61911),
    color = palette.bright_black,
    name = 'Bash',
  },
  ['c'] = {
    icon = i(61718),
    color = palette.bright_blue,
    name = 'C',
  },
  ['c++'] = {
    icon = i(61719),
    color = palette.bright_red,
    name = 'CPlusPlus',
  },
  ['cc'] = {
    icon = i(61719),
    color = palette.bright_red,
    name = 'CPlusPlus',
  },
  ['conf'] = {
    icon = i(61781),
    color = palette.bright_black,
    name = 'Conf',
  },
  ['cp'] = {
    icon = i(61719),
    color = palette.bright_blue,
    name = 'Cp',
  },
  ['cpp'] = {
    icon = i(61719),
    color = palette.bright_blue,
    name = 'Cpp',
  },
  ['css'] = {
    icon = i(61743),
    color = palette.bright_blue,
    name = 'Css',
  },
  ['dart'] = {
    icon = i(61744),
    color = palette.bright_blue,
    name = 'Dart',
  },
  ['db'] = {
    icon = i(61746),
    color = palette.bright_black,
    name = 'Db',
  },
  ['dockerfile'] = {
    icon = i(61758),
    color = palette.bright_blue,
    name = 'Dockerfile',
  },
  ['fish'] = {
    icon = i(61911),
    color = '#4d5a5e',
    name = 'Fish',
  },
  ['go'] = {
    icon = i(61789),
    color = palette.bright_blue,
    name = 'Go',
  },
  ['htm'] = {
    icon = i(61799),
    color = palette.bright_red,
    name = 'Htm',
  },
  ['html'] = {
    icon = i(61799),
    color = palette.bright_red,
    name = 'Html',
  },
  ['ico'] = {
    icon = i(61801),
    color = palette.yellow,
    name = 'Ico',
  },
  ['java'] = {
    icon = i(61809),
    color = palette.bright_red,
    name = 'Java',
  },
  ['jpeg'] = {
    icon = i(61801),
    color = palette.magenta,
    name = 'Jpeg',
  },
  ['jpg'] = {
    icon = i(61801),
    color = palette.magenta,
    name = 'Jpg',
  },
  ['js'] = {
    icon = i(61810),
    color = palette.yellow,
    name = 'Js',
  },
  ['json'] = {
    icon = i(61811),
    color = palette.bright_black,
    name = 'Json',
  },
  ['jsx'] = {
    icon = i(61867),
    color = palette.bright_blue,
    name = 'Jsx',
  },
  ['license'] = {
    icon = i(61767),
    color = palette.yellow,
    name = 'License',
  },
  lua = {
    icon = i(61826),
    color = palette.bright_blue,
    name = 'Lua',
  },
  ['makefile'] = {
    icon = i(61911),
    color = palette.bright_black,
    name = 'Makefile',
  },
  ['markdown'] = {
    icon = i(61829),
    color = palette.bright_blue,
    name = 'Markdown',
  },
  ['md'] = {
    icon = i(61829),
    color = palette.bright_white,
    name = 'Md',
  },
  ['mdx'] = {
    icon = i(61829),
    color = palette.bright_blue,
    name = 'Mdx',
  },
  ['node_modules'] = {
    icon = i(61840),
    color = palette.bright_red,
    name = 'NodeModules',
  },
  ['package.json'] = {
    icon = i(61843),
    color = palette.bright_red,
    name = 'PackageJson',
  },
  ['package-lock.json'] = {
    icon = i(61843),
    color = palette.bright_red,
    name = 'PackageLockJson',
  },
  ['php'] = {
    icon = i(61855),
    color = palette.magenta,
    name = 'Php',
  },
  ['pl'] = {
    icon = i(61853),
    color = palette.bright_blue,
    name = 'Pl',
  },
  ['png'] = {
    icon = i(61801),
    color = palette.magenta,
    name = 'Png',
  },
  ['py'] = {
    icon = i(61863),
    color = palette.bright_yellow,
    name = 'Py',
  },
  ['pyc'] = {
    icon = i(61863),
    color = palette.bright_blue,
    name = 'Pyc',
  },
  ['pyd'] = {
    icon = i(61863),
    color = palette.bright_blue,
    name = 'Pyd',
  },
  ['pyo'] = {
    icon = i(61863),
    color = palette.bright_blue,
    name = 'Pyo',
  },
  ['r'] = {
    icon = i(61866),
    color = palette.bright_green,
    name = 'R',
  },
  ['rake'] = {
    icon = i(61880),
    color = palette.bright_red,
    name = 'Rake',
  },
  ['rakefile'] = {
    icon = i(61880),
    color = palette.bright_red,
    name = 'Rakefile',
  },
  ['rb'] = {
    icon = i(61880),
    color = palette.bright_red,
    name = 'Rb',
  },
  ['rs'] = {
    icon = i(61881),
    color = palette.bright_black,
    name = 'Rs',
  },
  ['rss'] = {
    icon = i(61879),
    color = palette.orange,
    name = 'Rss',
  },
  ['scala'] = {
    icon = i(61882),
    color = palette.bright_red,
    name = 'Scala',
  },
  ['sh'] = {
    icon = i(61911),
    color = palette.bright_black,
    name = 'Sh',
  },
  ['sql'] = {
    icon = i(61746),
    color = palette.bright_black,
    name = 'Sql',
  },
  ['swift'] = {
    icon = i(61906),
    color = palette.orange,
    name = 'Swift',
  },
  ['toml'] = {
    icon = i(61916),
    color = palette.bright_black,
    name = 'Toml',
  },
  ['ts'] = {
    icon = i(61923),
    color = palette.bright_blue,
    name = 'Ts',
  },
  ['tsx'] = {
    icon = i(61867),
    color = palette.bright_blue,
    name = 'Tsx',
  },
  ['vim'] = {
    icon = i(61932),
    color = palette.bright_green,
    name = 'Vim',
  },
  ['vue'] = {
    icon = i(61940),
    color = palette.bright_green,
    name = 'Vue',
  },
  ['webp'] = {
    icon = i(61801),
    color = palette.magenta,
    name = 'Webp',
  },
  ['yaml'] = {
    icon = i(61945),
    color = palette.bright_black,
    name = 'Yaml',
  },
  ['yml'] = {
    icon = i(61945),
    color = palette.bright_black,
    name = 'Yml',
  },
  ['zsh'] = {
    icon = i(61911),
    color = palette.bright_black,
    name = 'Zsh',
  },
  ['terminal'] = {
    icon = i(61911),
    color = palette.bright_black,
    name = 'Terminal',
  },
  default_icon = { icon = '󰈚', name = 'Default' },
  deb = { icon = '', name = 'deb' },
  kt = { icon = '󱈙', name = 'kt' },
  lock = { icon = i(61823), name = 'lock' },
  mp3 = { icon = '󰎆', name = 'mp3' },
  mp4 = { icon = '', name = 'mp4' },
  out = { icon = '', name = 'out' },
  ['robots.txt'] = { icon = '󰚩', name = 'robots' },
  ttf = { icon = '', name = 'TrueTypeFont' },
  rpm = { icon = '', name = 'rpm' },
  woff = { icon = '', name = 'WebOpenFontFormat' },
  woff2 = { icon = '', name = 'WebOpenFontFormat2' },
  xz = { icon = '', name = 'xz' },
  zip = { icon = '', name = 'zip' },
  ['alert'] = { icon = i(61697), name = 'Alert' },
  ['angular'] = { icon = i(61698), name = 'Angular' },
  ['archive'] = { icon = i(61699) },
  ['arrow-both'] = { icon = i(61700) },
  ['arrow-down'] = { icon = i(61701) },
  ['arrow-left'] = { icon = i(61702) },
  ['arrow-right'] = { icon = i(61703) },
  ['arrow-switch'] = { icon = i(61704) },
  ['arrow-up'] = { icon = i(61705) },
  ['backbone'] = { icon = i(61706) },
  ['beaker'] = { icon = i(61707) },
  ['bell'] = { icon = i(61708) },
  ['bell-slash'] = { icon = i(61709) },
  ['bold'] = { icon = i(61710) },
  ['book'] = { icon = i(61711) },
  ['bookmark'] = { icon = i(61712) },
  ['bookmark-slash'] = { icon = i(61713) },
  ['briefcase'] = { icon = i(61714) },
  ['broadcast'] = { icon = i(61715) },
  ['browser'] = { icon = i(61716) },
  ['bug'] = { icon = i(61717) },
  ['c-plusplus'] = { icon = i(61719) },
  ['c-sharp'] = { icon = i(61720) },
  ['calendar'] = { icon = i(61721) },
  ['check'] = { icon = i(61722) },
  ['check-circle'] = { icon = i(61723) },
  ['check-circle-fill'] = { icon = i(61724) },
  ['checklist'] = { icon = i(61725) },
  ['chevron-down'] = { icon = i(61726) },
  ['chevron-left'] = { icon = i(61727) },
  ['chevron-right'] = { icon = i(61728) },
  ['chevron-up'] = { icon = i(61729) },
  ['circle'] = { icon = i(61730) },
  ['circle-slash'] = { icon = i(61731) },
  ['clippy'] = { icon = i(61732) },
  ['clock'] = { icon = i(61733) },
  ['code'] = { icon = i(61734) },
  ['code-review'] = { icon = i(61735) },
  ['code-square'] = { icon = i(61736) },
  ['comment'] = { icon = i(61737) },
  ['comment-discussion'] = { icon = i(61738) },
  ['container'] = { icon = i(61739) },
  ['cpu'] = { icon = i(61740) },
  ['credit-card'] = { icon = i(61741) },
  ['cross-reference'] = { icon = i(61742) },
  ['dash'] = { icon = i(61745) },
  ['database'] = { icon = i(61746) },
  ['desktop-download'] = { icon = i(61747) },
  ['device-camera'] = { icon = i(61748) },
  ['device-camera-video'] = { icon = i(61749) },
  ['device-desktop'] = { icon = i(61750) },
  ['device-mobile'] = { icon = i(61751) },
  ['diff'] = { icon = i(61752) },
  ['diff-added'] = { icon = i(61753) },
  ['diff-ignored'] = { icon = i(61754) },
  ['diff-modified'] = { icon = i(61755) },
  ['diff-removed'] = { icon = i(61756) },
  ['diff-renamed'] = { icon = i(61757) },
  ['docker'] = { icon = i(61758) },
  ['dot'] = { icon = i(61759) },
  ['dot-fill'] = { icon = i(61760) },
  ['download'] = { icon = i(61761) },
  ['ellipsis'] = { icon = i(61762) },
  ['elm'] = { icon = i(61763) },
  ['eye'] = { icon = i(61764) },
  ['eye-closed'] = { icon = i(61765) },
  ['file'] = { icon = i(61766) },
  ['file-badge'] = { icon = i(61767) },
  ['file-binary'] = { icon = i(61768) },
  ['file-code'] = { icon = i(61769) },
  ['file-diff'] = { icon = i(61770) },
  ['file-directory'] = { icon = i(61771) },
  ['file-directory-outline'] = { icon = i(61772) },
  ['file-submodule'] = { icon = i(61773) },
  ['file-symlink-file'] = { icon = i(61774) },
  ['file-zip'] = { icon = i(61775) },
  ['filter'] = { icon = i(61776) },
  ['flame'] = { icon = i(61777) },
  ['fold'] = { icon = i(61778) },
  ['fold-down'] = { icon = i(61779) },
  ['fold-up'] = { icon = i(61780) },
  ['gear'] = { icon = i(61781) },
  ['gift'] = { icon = i(61782) },
  ['git-branch'] = { icon = i(61783) },
  ['git-commit'] = { icon = i(61784) },
  ['git-compare'] = { icon = i(61785) },
  ['git-merge'] = { icon = i(61786) },
  ['git-pull-request'] = { icon = i(61787) },
  ['globe'] = { icon = i(61788) },
  ['grabber'] = { icon = i(61790) },
  ['graph'] = { icon = i(61791) },
  ['heading'] = { icon = i(61792) },
  ['heart'] = { icon = i(61793) },
  ['heart-fill'] = { icon = i(61794) },
  ['history'] = { icon = i(61795) },
  ['home'] = { icon = i(61796) },
  ['horizontal-rule'] = { icon = i(61797) },
  ['hourglass'] = { icon = i(61798) },
  ['hubot'] = { icon = i(61800) },
  ['image'] = { icon = i(61801) },
  ['inbox'] = { icon = i(61802) },
  ['infinity'] = { icon = i(61803) },
  ['info'] = { icon = i(61804) },
  ['issue-closed'] = { icon = i(61805) },
  ['issue-opened'] = { icon = i(61806) },
  ['issue-reopened'] = { icon = i(61807) },
  ['italic'] = { icon = i(61808) },
  ['javascript'] = { icon = i(61810) },
  ['kebab-horizontal'] = { icon = i(61812) },
  ['key'] = { icon = i(61813) },
  ['kotlin'] = { icon = i(61814) },
  ['kubernetes'] = { icon = i(61815) },
  ['law'] = { icon = i(61816) },
  ['light-bulb'] = { icon = i(61817) },
  ['link'] = { icon = i(61818) },
  ['link-external'] = { icon = i(61819) },
  ['list-ordered'] = { icon = i(61820) },
  ['list-unordered'] = { icon = i(61821) },
  ['location'] = { icon = i(61822) },
  ['logo-gist'] = { icon = i(61824) },
  ['logo-github'] = { icon = i(61825) },
  ['mail'] = { icon = i(61827) },
  ['mark-github'] = { icon = i(61828) },
  ['megaphone'] = { icon = i(61830) },
  ['mention'] = { icon = i(61831) },
  ['meter'] = { icon = i(61832) },
  ['milestone'] = { icon = i(61833) },
  ['mirror'] = { icon = i(61834) },
  ['moon'] = { icon = i(61835) },
  ['mortar-board'] = { icon = i(61836) },
  ['mute'] = { icon = i(61837) },
  ['nginx'] = { icon = i(61838) },
  ['no-entry'] = { icon = i(61839) },
  ['node'] = { icon = i(61840) },
  ['north-star'] = { icon = i(61841) },
  ['note'] = { icon = i(61842) },
  ['npm'] = { icon = i(61843) },
  ['octoface'] = { icon = i(61844) },
  ['organization'] = { icon = i(61845) },
  ['package'] = { icon = i(61846) },
  ['package-dependencies'] = { icon = i(61847) },
  ['package-dependents'] = { icon = i(61848) },
  ['paintbrush'] = { icon = i(61849) },
  ['paper-airplane'] = { icon = i(61850) },
  ['pencil'] = { icon = i(61851) },
  ['people'] = { icon = i(61852) },
  ['perl'] = { icon = i(61853) },
  ['person'] = { icon = i(61854) },
  ['pin'] = { icon = i(61856) },
  ['play'] = { icon = i(61857) },
  ['plug'] = { icon = i(61858) },
  ['plus'] = { icon = i(61859) },
  ['plus-circle'] = { icon = i(61860) },
  ['project'] = { icon = i(61861) },
  ['pulse'] = { icon = i(61862) },
  ['python'] = { icon = i(61863) },
  ['question'] = { icon = i(61864) },
  ['quote'] = { icon = i(61865) },
  ['react'] = { icon = i(61867) },
  ['rectangle'] = { icon = i(61868) },
  ['reply'] = { icon = i(61869) },
  ['repo'] = { icon = i(61870) },
  ['repo-clone'] = { icon = i(61871) },
  ['repo-forked'] = { icon = i(61872) },
  ['repo-pull'] = { icon = i(61873) },
  ['repo-push'] = { icon = i(61874) },
  ['repo-template'] = { icon = i(61875) },
  ['report'] = { icon = i(61876) },
  ['require'] = { icon = i(61877) },
  ['rocket'] = { icon = i(61878) },
  ['ruby'] = { icon = i(61880) },
  ['rust'] = { icon = i(61881) },
  ['screen-full'] = { icon = i(61883) },
  ['screen-normal'] = { icon = i(61884) },
  ['search'] = { icon = i(61885) },
  ['server'] = { icon = i(61886) },
  ['share'] = { icon = i(61887) },
  ['share-android'] = { icon = i(61888) },
  ['shield'] = { icon = i(61889) },
  ['shield-check'] = { icon = i(61890) },
  ['shield-lock'] = { icon = i(61891) },
  ['shield-x'] = { icon = i(61892) },
  ['sign-in'] = { icon = i(61893) },
  ['sign-out'] = { icon = i(61894) },
  ['skip'] = { icon = i(61895) },
  ['smiley'] = { icon = i(61896) },
  ['square'] = { icon = i(61897) },
  ['square-fill'] = { icon = i(61898) },
  ['squirrel'] = { icon = i(61899) },
  ['star'] = { icon = i(61900) },
  ['star-fill'] = { icon = i(61901) },
  ['stop'] = { icon = i(61902) },
  ['stopwatch'] = { icon = i(61903) },
  ['strikethrough'] = { icon = i(61904) },
  ['sun'] = { icon = i(61905) },
  ['sync'] = { icon = i(61907) },
  ['tag'] = { icon = i(61908) },
  ['tasklist'] = { icon = i(61909) },
  ['telescope'] = { icon = i(61910) },
  ['three-bars'] = { icon = i(61912) },
  ['thumbsdown'] = { icon = i(61913) },
  ['thumbsup'] = { icon = i(61914) },
  ['tmux'] = { icon = i(61915) },
  ['tools'] = { icon = i(61917) },
  ['trashcan'] = { icon = i(61918) },
  ['triangle-down'] = { icon = i(61919) },
  ['triangle-left'] = { icon = i(61920) },
  ['triangle-right'] = { icon = i(61921) },
  ['triangle-up'] = { icon = i(61922) },
  ['typescript'] = { icon = i(61923) },
  ['typography'] = { icon = i(61924) },
  ['unfold'] = { icon = i(61925) },
  ['unlock'] = { icon = i(61926) },
  ['unmute'] = { icon = i(61927) },
  ['unverified'] = { icon = i(61928) },
  ['upload'] = { icon = i(61929) },
  ['verified'] = { icon = i(61930) },
  ['versions'] = { icon = i(61931) },
  ['vim-command-mode'] = { icon = i(61933) },
  ['vim-insert-mode'] = { icon = i(61934) },
  ['vim-normal-mode'] = { icon = i(61935) },
  ['vim-replace-mode'] = { icon = i(61936) },
  ['vim-select-mode'] = { icon = i(61937) },
  ['vim-terminal-mode'] = { icon = i(61938) },
  ['vim-visual-mode'] = { icon = i(61939) },
  ['workflow'] = { icon = i(61941) },
  ['x'] = { icon = i(61942) },
  ['x-circle'] = { icon = i(61943) },
  ['x-circle-fill'] = { icon = i(61944) },
  ['yarn'] = { icon = i(61946) },
  ['zap'] = { icon = i(61947) },
  ['multi-select'] = { icon = i(61948) },
  ['number'] = { icon = i(61949) },
  ['trash'] = { icon = i(61950) },
  ['video'] = { icon = i(61951) },
  ['class'] = { icon = i(61952) },
  ['constant'] = { icon = i(61953) },
  ['field'] = { icon = i(61954) },
  ['interface'] = { icon = i(61955) },
  ['keyword'] = { icon = i(61956) },
  ['snippet'] = { icon = i(61957) },
  ['struct'] = { icon = i(61958) },
  ['type'] = { icon = i(61959) },
  ['variable'] = { icon = i(61960) },
  ['blocked'] = { icon = i(61961) },
  ['codescan'] = { icon = i(61962) },
  ['codescan-checkmark'] = { icon = i(61963) },
  ['codespaces'] = { icon = i(61964) },
  ['dependabot'] = { icon = i(61965) },
  ['duplicate'] = { icon = i(61966) },
  ['person-add'] = { icon = i(61967) },
  ['sidebar-collapse'] = { icon = i(61968) },
  ['sidebar-expand'] = { icon = i(61969) },
  ['table'] = { icon = i(61970) },
  ['elixir'] = { icon = i(61971) },
  ['terraform'] = { icon = i(61972) },
  ['columns'] = { icon = i(61973) },
  ['diamond'] = { icon = i(61974) },
  ['git-pull-request-closed'] = { icon = i(61975) },
  ['git-pull-request-draft'] = { icon = i(61976) },
  ['hash'] = { icon = i(61977) },
  ['issue-draft'] = { icon = i(61978) },
  ['rows'] = { icon = i(61979) },
  ['select-single'] = { icon = i(61980) },
  ['eslint'] = { icon = i(61981) },
  ['prettier'] = { icon = i(61982) },
  ['vscode'] = { icon = i(61983) },
  ['copy'] = { icon = i(61984) },
  ['key-asterisk'] = { icon = i(61985) },
  ['paste'] = { icon = i(61986) },
  ['sort-asc'] = { icon = i(61987) },
  ['sort-desc'] = { icon = i(61988) },
  ['babel'] = { icon = i(61989) },
  ['ionic'] = { icon = i(61990) },
  ['next'] = { icon = i(61991) },
  ['svelte'] = { icon = i(61992) },
  ['capacitor'] = { icon = i(61993) },
  ['graphql'] = { icon = i(61994) },
  ['accessibility'] = { icon = i(61995) },
  ['apps'] = { icon = i(61996) },
  ['bell-fill'] = { icon = i(61997) },
  ['cloud'] = { icon = i(61998) },
  ['cloud-offline'] = { icon = i(61999) },
  ['code-of-conduct'] = { icon = i(62000) },
  ['feed-discussion'] = { icon = i(62001) },
  ['feed-forked'] = { icon = i(62002) },
  ['feed-heart'] = { icon = i(62003) },
  ['feed-merged'] = { icon = i(62004) },
  ['feed-person'] = { icon = i(62005) },
  ['feed-repo'] = { icon = i(62006) },
  ['feed-rocket'] = { icon = i(62007) },
  ['feed-star'] = { icon = i(62008) },
  ['feed-tag'] = { icon = i(62009) },
  ['feed-trophy'] = { icon = i(62010) },
  ['file-directory-fill'] = { icon = i(62011) },
  ['file-directory-open-fill'] = { icon = i(62012) },
  ['id-badge'] = { icon = i(62013) },
  ['iterations'] = { icon = i(62014) },
  ['log'] = { icon = i(62015) },
  ['person-fill'] = { icon = i(62016), name = 'Person-fill' },
  ['repo-deleted'] = { icon = i(62017), name = 'Repo-deleted' },
  ['repo-locked'] = { icon = i(62018), name = 'Repo-locked' },
  ['single-select'] = { icon = i(62019), name = 'Single-select' },
  ['sliders'] = { icon = i(62020), name = 'Sliders' },
  ['stack'] = { icon = i(62021), name = 'Stack' },
  ['tab-external'] = { icon = i(62022), name = 'Tab-external' },
  ['telescope-fill'] = { icon = i(62023), name = 'Telescope-fill' },
  ['trophy'] = { icon = i(62024), name = 'Trophy' },
  ['webhook'] = { icon = i(62025), name = 'Webhook' },
}
